name: Conventional Commit Checker

on:
  push: {}
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize, edited, ready_for_review]

jobs:
  conventional-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Conventional Commits
        uses: webiny/action-conventional-commits@v1.3.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
